openapi: 3.0.1
info:
  title: 백투더퓨처 API Documentation
  description: 백투더퓨처 API 문서입니다.
  version: v1.0.0
servers:
- url: http://localhost:8084/v1
  description: Generated server url
security:
- Authorization: []
tags:
- name: certificate
  description: 인증 API
paths:
  /certificate/email:
    get:
      tags:
      - certificate
      summary: 이메일 인증 번호 검증 API
      description: 이메일과 인증 번호를 사용하여 인증 번호의 유효성을 검증합니다.
      operationId: verifyMailCertificationNumber
      parameters:
      - name: email
        in: query
        description: 이메일 주소
        required: true
        schema:
          type: string
      - name: certificationNumber
        in: query
        description: 인증 번호
        required: true
        schema:
          type: string
      responses:
        "200":
          description: 인증 번호 유효성 검사 결과
          content:
            application/json:
              examples:
                valid certification number:
                  description: valid certification number
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: true
                invalid certification number:
                  description: invalid certification number
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      isValid: false
      security: []
    post:
      tags:
      - certificate
      summary: 인증코드 메일 전송 API
      description: 이메일로 인증코드를 전송합니다.
      operationId: sendCertificateMail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailCertificateRequestDto'
        required: true
      responses:
        "400":
          description: 이메일 형식에 맞지 않습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid email:
                  description: invalid email
                  value:
                    errorCode: 400
                    errorMessage: 입력값에 대한 검증에 실패했습니다.
                    validation:
                      email: 이메일 형식에 맞지 않습니다.
        "200":
          description: 인증 번호 발송 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BfResponseCertificateMailResponseDto'
      security: []
components:
  schemas:
    MailCertificateRequestDto:
      required:
      - email
      type: object
      properties:
        email:
          pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,6}$"
          type: string
          description: 사용자 이메일 주소
          example: user@example.com
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: integer
          format: int32
        errorMessage:
          type: string
        validation:
          type: object
          additionalProperties:
            type: string
    BfResponseCertificateMailResponseDto:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          $ref: '#/components/schemas/CertificateMailResponseDto'
    CertificateMailResponseDto:
      type: object
      properties:
        mailExpirationSeconds:
          type: integer
          description: 인증 번호 유효 시간(초)
          format: int32
          example: 600
        certificationNumber:
          type: string
          description: 인증 번호
          example: "123456"
      description: 응답 데이터
  securitySchemes:
    Authorization:
      type: http
      name: Authorization
      scheme: bearer
      bearerFormat: JWT
