openapi: 3.0.1
info:
  title: 백투더퓨처 API Documentation
  description: 백투더퓨처 API 문서입니다.
  version: v1.0.0
servers:
- url: http://localhost:8081/v1
  description: Generated server url
security:
- Authorization: []
tags:
- name: 예약(주문) API
  description: 예약 관련 API 입니다.
- name: 찜 API
  description: 찜 관련 API 입니다.
- name: 상품 API
  description: 상품 관련 API 입니다.
- name: 가게 API
  description: 가게 관련 API 입니다.
paths:
  /stores:
    post:
      tags:
      - 가게 API
      summary: 새로운 가게 등록
      description: "가게 정보와 이미지를 등록합니다. 이미지는 'image/png', 'image/jpeg' 형식을 지원합니다."
      operationId: registerStore
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - request
              type: object
              properties:
                request:
                  $ref: '#/components/schemas/StoreRegisterDto'
                file:
                  type: string
                  description: 가게 이미지로 사용할 이미지를 첨부해 주세요.
                  format: binary
      responses:
        "201":
          description: 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BfResponse'
              examples:
                success:
                  description: success
                  value:
                    code: 201
                    message: 정상적으로 생성되었습니다.
                    data:
                      store_id: 1
  /stores/{storeId}/products:
    post:
      tags:
      - 상품 API
      summary: 새로운 상품 등록
      description: "특정 가게에 새로운 상품을 등록합니다. 이미지는 'image/png', 'image/jpeg' 형식을 지원합니다\
        ."
      operationId: registerProduct
      parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - request
              type: object
              properties:
                request:
                  $ref: '#/components/schemas/ProductRegisterDto'
                file:
                  type: string
                  description: 상품 이미지로 사용할 이미지를 첨부해 주세요.
                  format: binary
      responses:
        "201":
          description: 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BfResponse'
              examples:
                success:
                  description: success
                  value:
                    code: 201
                    message: 정상적으로 생성되었습니다.
                    data:
                      product_id: 1
  /stores/{storeId}/likes/{memberId}:
    post:
      tags:
      - 찜 API
      summary: 상점 찜 등록
      description: 특정 상점에 대해 특정 사용자가 찜을 등록합니다.
      operationId: addLike
      parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: memberId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 찜 추가 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BfResponse'
              examples:
                success:
                  description: success
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data: SUCCESS
    delete:
      tags:
      - 찜 API
      summary: 상점 찜 취소
      description: 특정 상점에 대해 특정 사용자의 찜을 취소합니다.
      operationId: removeLike
      parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: memberId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: 찜 취소 성공
  /reservations:
    post:
      tags:
      - 예약(주문) API
      summary: 주문
      description: 주문 요청 API입니다.
      operationId: makeReservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationRequestDto'
        required: true
      responses:
        "200":
          description: 예약(주문) 성공 응답입니다.
          content:
            '*/*':
              examples:
                주문 번호:
                  description: 주문 번호
                  value:
                    code: 200
                    message: 정상 처리되었습니다.
                    data:
                      reservation_id: 1
  /stores/{storeId}/products/{productId}:
    get:
      tags:
      - 상품 API
      summary: 상품 정보 조회
      description: 특정 가게의 특정 상품에 대한 자세한 정보를 조회합니다.
      operationId: getProduct
      parameters:
      - name: storeId
        in: path
        description: 가게 ID
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        description: 상품 ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseProductGetOneResponseDto'
      security: []
    delete:
      tags:
      - 상품 API
      summary: 싱픔 삭제
      operationId: deleteProduct
      parameters:
      - name: storeId
        in: path
        description: 가게 ID
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        description: 상품 ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: 삭제 성공
    patch:
      tags:
      - 상품 API
      summary: 상품 부분 수정
      description: "상품 정보를 부분적으로 수정합니다. 수정하지 않는 정보는 요청 정보에 포함하지 않습니다. 이미지는 'image/png',\
        \ 'image/jpeg' 형식을 지원합니다."
      operationId: updateProduct
      parameters:
      - name: storeId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: productId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - request
              type: object
              properties:
                request:
                  $ref: '#/components/schemas/ProductUpdateDto'
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BfResponseProductGetOneResponseDto'
  /reservations/{reservationId}:
    get:
      tags:
      - 예약(주문) API
      operationId: getReservation
      parameters:
      - name: reservationId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
    delete:
      tags:
      - 예약(주문) API
      operationId: cancelReservation
      parameters:
      - name: reservationId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseObject'
  /reservations/proceeding:
    get:
      tags:
      - 예약(주문) API
      summary: 주문 진행 내역
      description: 주문 진행 내역 조회 API입니다.
      operationId: getMemberProceedingReservations
      responses:
        "200":
          description: 주문 진행 내역 조회 성공 응답입니다.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseListMemberProgressReservationResponseDto'
  /reservations/done:
    get:
      tags:
      - 예약(주문) API
      summary: 주문 완료 내역
      description: 주문 완료 내역 조회 API입니다.
      operationId: getMemberDoneReservations
      parameters:
      - name: cursorId
        in: query
        description: 마지막으로 조회한 주문 id 값입니다.
        required: true
        schema:
          type: integer
          format: int64
      - name: size
        in: query
        description: 페이지 크기입니다.
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: 주문 완료 내역 조회 성공 응답입니다.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseMemberDoneReservationResponseDto'
  /products:
    get:
      tags:
      - 상품 API
      summary: 모든 상품 정보 조회
      description: "모든 상품을 조회합니다. TODO: 정렬기준, pagenation 추가"
      operationId: getAllProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BfResponseProductGetListResponseDto'
      security: []
components:
  schemas:
    BfResponse:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          type: object
          description: 응답 데이터
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
      description: 마감 시간
      example: 22:00
    StoreRegisterDto:
      required:
      - description
      - endTime
      - location
      - name
      - startTime
      type: object
      properties:
        name:
          maxLength: 20
          minLength: 0
          type: string
          description: 가게 이름
          example: 베이커리 카페
        description:
          maxLength: 50
          minLength: 0
          type: string
          description: 가게 설명
          example: 신선한 빵과 커피를 제공하는 카페
        location:
          maxLength: 50
          minLength: 0
          type: string
          description: 가게 위치
          example: 서울시 강남구 역삼동 123-45
        contact:
          type: array
          description: 가게 연락처
          example:
          - "010"
          - "0000"
          - "0000"
          items:
            type: string
        startTime:
          $ref: '#/components/schemas/LocalTime'
        endTime:
          $ref: '#/components/schemas/LocalTime'
      description: 요청 정보입니다.
    ProductRegisterDto:
      required:
      - description
      - name
      - price
      type: object
      properties:
        name:
          maxLength: 20
          minLength: 0
          type: string
          description: 상품 이름
          example: 크루아상
        description:
          maxLength: 50
          minLength: 0
          type: string
          description: 상품 설명
          example: 프랑스 고메버터가 풍부하게 들어간 프랑스식 패스트리
        price:
          maximum: 1000000
          minimum: 0
          type: integer
          description: "상품 가격 (단위: 원)"
          format: int32
          example: 3000
        stockQuantity:
          minimum: 0
          type: integer
          description: "재고 수량 (기본값: 0)"
          format: int32
          example: 50
      description: 요청 정보입니다.
    ReservationRequestDto:
      required:
      - reservationTime
      - storeId
      type: object
      properties:
        storeId:
          type: integer
          description: 가게 id 값입니다.
          format: int64
        orderRequestItems:
          maxItems: 2147483647
          minItems: 1
          type: array
          description: 예약 상품 값들입니다.
          items:
            $ref: '#/components/schemas/ReservationRequestItemDto'
        reservationTime:
          type: string
          description: 예약(주문) 요청 시간입니다.
          format: date-time
      description: 예약(주문)하기 요청 model입니다.
    ReservationRequestItemDto:
      required:
      - productId
      type: object
      properties:
        productId:
          type: integer
          description: 상품 id 값입니다.
          format: int64
        quantity:
          minimum: 0
          type: integer
          description: 주문 수량입니다.
          format: int32
      description: 예약 상품 model입니다.
    ProductUpdateDto:
      type: object
      properties:
        name:
          maxLength: 20
          minLength: 0
          type: string
        description:
          maxLength: 50
          minLength: 0
          type: string
        price:
          maximum: 1000000
          minimum: 0
          type: integer
          format: int32
        stockQuantity:
          minimum: 0
          type: integer
          format: int32
    BfResponseProductGetOneResponseDto:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          $ref: '#/components/schemas/ProductGetOneResponseDto'
    ProductGetOneResponseDto:
      type: object
      properties:
        product:
          $ref: '#/components/schemas/ProductResponseDto'
      description: 응답 데이터
    ProductResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int32
        stockQuantity:
          type: integer
          format: int32
        thumbnail:
          type: string
    BfResponseObject:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          type: object
          description: 응답 데이터
    BfResponseListMemberProgressReservationResponseDto:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          type: array
          description: 응답 데이터
          items:
            $ref: '#/components/schemas/MemberProgressReservationResponseDto'
    MemberProgressReservationResponseDto:
      type: object
      properties:
        storeImg:
          type: string
          description: 가게 이미지입니다.
        name:
          type: string
          description: 가게 이름입니다.
        reservationId:
          type: integer
          description: 가게 id 값입니다.
          format: int64
        reservationTime:
          type: string
          description: 예약(주문) 접수 시간입니다.
          format: date-time
        totalPrice:
          type: integer
          description: 주문 총 금액입니다.
          format: int32
        productNames:
          type: array
          description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은 productName\
            \ 입니다."
          items:
            type: object
            additionalProperties:
              type: string
              description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은\
                \ productName 입니다."
            description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은 productName\
              \ 입니다."
        reservationHistory:
          type: array
          description: |-
            주문 진행 내역입니다. json key 값은REGISTRATION, // 예약 접수
            CONFIRMATION, // 예약 확정
            PICKUP_WAITING, // 픽업 대기
            PICKUP_DONE; // 픽업 완료
            중 하나입니다.
          items:
            type: object
            additionalProperties:
              type: string
              description: |-
                주문 진행 내역입니다. json key 값은REGISTRATION, // 예약 접수
                CONFIRMATION, // 예약 확정
                PICKUP_WAITING, // 픽업 대기
                PICKUP_DONE; // 픽업 완료
                중 하나입니다.
              format: date-time
            description: |-
              주문 진행 내역입니다. json key 값은REGISTRATION, // 예약 접수
              CONFIRMATION, // 예약 확정
              PICKUP_WAITING, // 픽업 대기
              PICKUP_DONE; // 픽업 완료
              중 하나입니다.
      description: 주문 진행 응답 model 입니다.
    BfResponseMemberDoneReservationResponseDto:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          $ref: '#/components/schemas/MemberDoneReservationResponseDto'
    MemberDoneReservationListDto:
      type: object
      properties:
        storeImg:
          type: string
          description: 가게 이미지입니다.
        name:
          type: string
          description: 가게 이름입니다.
        reservationId:
          type: integer
          description: 예약(주문) id 값입니다.
          format: int64
        reservationTime:
          type: string
          description: 예약(주문) 접수 시간입니다.
          format: date-time
        totalPrice:
          type: integer
          description: 주문 전체 금액입니다.
          format: int32
        productNames:
          type: array
          description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은 productName\
            \ 입니다."
          items:
            type: object
            additionalProperties:
              type: string
              description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은\
                \ productName 입니다."
            description: "예약(주문) 상품 이름입니다. 'productName : 이름' 형태입니다. json key 값은 productName\
              \ 입니다."
      description: 완료된 주문 정보 model입니다.
    MemberDoneReservationResponseDto:
      type: object
      properties:
        memberDoneReservationList:
          type: array
          description: 주문 정보 값들입니다.
          items:
            $ref: '#/components/schemas/MemberDoneReservationListDto'
        isLast:
          type: boolean
          description: 다음 페이지 존재 여부입니다.
      description: 주문 완료 내역 조회 model입니다.
    BfResponseProductGetListResponseDto:
      type: object
      properties:
        code:
          type: integer
          description: 응답 코드
          format: int32
          example: 200
        message:
          type: string
          description: 응답 메시지
          example: 성공
        data:
          $ref: '#/components/schemas/ProductGetListResponseDto'
    ProductGetListResponseDto:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponseDto'
      description: 응답 데이터
  securitySchemes:
    Authorization:
      type: http
      name: Authorization
      scheme: bearer
      bearerFormat: JWT
